apiVersion: v1
kind: ConfigMap
metadata:
 name: sample-config
data:
  sample.cfg:
    : tsuyoshi.tanaka
  type: "application"
  

---

apiVersion: v1
  kind: Pod
  metadata:
    name: sample
  spec:
    containers:
    - name: sample
      image: nginx:1.17.20alpine
      env:
      - name: TYPE
        valueFrom:
          configMapKeyRef:
            name: sample-config
            key: type
      vokumeMounts:
      - name: config-storage
        mountPath: /home/nginx
    valumes:
    - name: config-storage
      configMap:
        name: sample-config
        items:
        - key: sample.cfg
          path: sample.cfg